<?php require_once 'layout/header.phtml'; ?>
<main>
<h2>Iniciar Sesion</h2>
<form action="inicio" method="POST">
    <div class="form-group">
            <label for="usuario">Usuario:</label>
            <input type="text" id="nombre" name="usuario" required>
        </div>
        <div class="form-group">
            <label for="contraseña">Contraseña:</label>
            <input type="password" id="nombre" name="contraseña" required>
        </div>
        <div class="form-group">
            <label for="email">Correo Electronico:</label>
            <input type="text" id="nombre" name="email" required>
        </div>
        <button type="submit" class="">Iniciar Secion</button>
</form>
</main>