<?php require_once 'layout/header.phtml'; ?>
<main>
    <h2>Agregar un nuevo bolso</h2>
    <form action="agregar" method="POST" class="form-bolso">
        <div class="form-group">
            <label for="nombre">Nombre del bolso:</label>
            <input type="text" id="nombre" name="nombre" required>
        </div>

        <div class="form-group">
            <label for="categoria">Categoría:</label>
            <select name="categoria" id="categoria">
    <?php
        if (!empty($categorias)) {
            foreach ($categorias as $categoria): ?>
                <option value="<?php echo $categoria->id_categoria; ?>">
                    <?php echo $categoria->Categoria; ?>
                </option>
            <?php endforeach;
        } else {
            echo '<option value="">No hay categorías disponibles</option>';
        }
    ?>
    </select>   
    </div>
        <div class="form-group">
        <label for="color">Color:</label>
    <select name="color" id="color" required>
    <option value="Rojo">Rojo</option>
    <option value="Azul">Azul</option>
    <option value="Negro">Negro</option>
    <option value="Verde">Verde</option>
    <option value="Amarillo">Amarillo</option>
    <option value="Blanco">Blanco</option>
    <option value="Gris">Gris</option>
</select>
        </div>
        

        <div class="form-group">
            <label for="precio">Precio:</label>
            <input type="number" id="precio" name="precio" required>
        </div>

        <button type="submit">Agregar Bolsos</button>
    </form>
</main>

<?php require_once 'layout/footer.phtml'; ?>
