<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Proyecto de Bolsos</title>
    <link rel="stylesheet" href="css/style.css">    
</head>
<body>
    <header>
        <h1>Bienvenidos a la tienda de Bolsos</h1>
        <nav>
            <ul>
                <li class="nav1"><a href="<?php echo BASE_URL; ?>bolsos">Inicio</a></li>
                <li class="nav1"><a href="<?php echo BASE_URL; ?>formulario">Agregar Bolsos</a></li>
                <li class="nav1"><a href="<?php echo BASE_URL; ?>bolsos">Lista de Bolsos</a></li>
                <li class="nav1"><a href="<?php echo BASE_URL; ?>categorias">Categorias</a></li>
                <li class="nav1"><a href="<?php echo BASE_URL; ?>cuenta">Cuenta</a></li>
                <li class="nav1"><a href="<?php echo BASE_URL; ?>formulario2">Agregar Categoria</a></li>
            </form>
        </li>
            </ul>
        </nav>
    </header>